#include "aphelion.h"

instr_template templates[] = {
    {"int",
        .args   = {arg_val_or_sym},
        .fields = {field_imm},
        .count  = 1,
        .opcode = 0x01,
        .func   = 0x00,
        .format = fmt_F},
    {"iret",
        .args   = NULL,
        .fields = NULL,
        .count  = 0,
        .opcode = 0x01,
        .func   = 0x01,
        .format = fmt_F},
    {"ires",
        .args   = NULL,
        .fields = NULL,
        .count  = 0,
        .opcode = 0x01,
        .func   = 0x02,
        .format = fmt_F},
    {"usr",
        .args   = {arg_register},
        .fields = {field_rde},
        .count  = 1,
        .opcode = 0x01,
        .func   = 0x03,
        .format = fmt_F},
    
    {"outr",
        .args   = {arg_register, arg_register},
        .fields = {field_rde,    field_rs1},
        .count  = 2,
        .opcode = 0x02,
        .func   = 0x00,
        .format = fmt_M},
    {"outi",
        .args   = {arg_val_or_sym, arg_register},
        .fields = {field_imm,      field_rs1},
        .count  = 2,
        .opcode = 0x03,
        .func   = 0x00,
        .format = fmt_M},
    {"inr",
        .args   = {arg_register, arg_register},
        .fields = {field_rde,  field_rs1},
        .count  = 2,
        .opcode = 0x04,
        .func   = 0x00,
        .format = fmt_M},
    {"ini",
        .args   = {arg_register, arg_val_or_sym},
        .fields = {field_rde,    field_imm},
        .count  = 2,
        .opcode = 0x05,
        .func   = 0x00,
        .format = fmt_M},
};